### ISSUE TITLE
Enhancement .Display in terminal window

### ISSUE THREAD

**Issue by pykong** [wvlia5/SublimeDebugger#1]
Instead of multiple smaller sub-panes, which cost quite some screen estate due to their tab bar, why not implement the entire output in a terminal window?

With terminal window I mean one from a terminal emulator, like the awesome [TerminalView](https://github.com/Wramberg/TerminalView).

**Comment by matiasmorant** [comment]
I guess you mean screen SPACE
Why would you want the output in a terminal? I don't get it 
If space taken by tab bars is a problem, it could be implemented in a single tab
But i don't think tab space is such a problem. In fact, multiple tabs allow you to close de ones you are not interested in

**Comment by pykong** [comment]
@wvlia5 Your points are all valid. I was just portraying my own idea of how your debugger should work.
I really like the idea of having a full blown python debugger right in Sublime. This transforms a simple editor into a complete IDE.

So, far I am using pudb in TerminalView for debugging purposes, yet I'd really like to have it all right in Sublime itself. Especially marking the active line, instead of seeing the same lines of code in a different window, is a great benefit.

Just my ideas. 

Anyway thanks for putting your effort in to develop this plugin! I just opened a PR as my contribution to it:
[https://github.com/wvlia5/SublimeDebugger/pull/2](https://github.com/wvlia5/SublimeDebugger/pull/2)

**Comment by matiasmorant** [comment]
Thanks! Yes i think this plugin is great. I was amazed it didn't exist before. 
Have a look at Sublime Ruby Debugger, they put tabs horizontally, maybe that would be a better layout? (it would only take the height of a single tab bar from tge screen) However, global&local variables info is always quite long, so you would have to increase total height of output panel for it to be useful
