### ISSUE TITLE
Upload on Package Control?

### ISSUE THREAD

**Issue by karanrajpal14** [wvlia5/SublimeDebugger#13]
Would you please upload this on Package Control? Would make it easier to keep it updated.

**Comment by matiasmorant** [comment]
I have. It's there, isn't it? 
https://packagecontrol.io/packages/Python%20Debugger
Why couldn't you find it?

**Comment by karanrajpal14** [comment]
My bad. I see it now, probably something wrong with on my end. Sorry for the trouble.
