### ISSUE TITLE
Tools>Debugger>Set Language - greyed out

### ISSUE THREAD

**Issue by ghost** [wvlia5/SublimeDebugger#18]
After installing on ST (Win10, Python 3 installed) I cannot select the language in the tools>debugger>set language menu. Both options for Python2 and 3 are greyed out.
Could you add short instructions how to set it up properly and any dependencies that are needed?

**Comment by matiasmorant** [comment]
This is probably related to

https://github.com/wvlia5/SublimeDebugger/issues/14

which arises when you don't have Python 2 installed (having it installed shouldn't be a requirement). 

If you look at ST console, it will give you further hints.

This issue is next on my list.

**Comment by ghost** [comment]
Thanks for the quick answer.

After further investigating the problem, I indeed get the same error messages as in [#14](https://github.com/wvlia5/SublimeDebugger/issues/14).
But even after removing the package from ST3, installing Python 2.7 and adding the package again, I get the same error messages.
Do I have to specify the Python installation path in any way?

**Comment by matiasmorant** [comment]
The python 2 debugger will launch a process executing the `python2` command (even if you never intend to debug Python 2 code, my bad)
 
As far as I know, if you open a terminal and can successfully run `python2`, this package should also work.

**Comment by matiasmorant** [comment]
Solved
