### ISSUE TITLE
Plugin marked as ignored package

### ISSUE THREAD

**Issue by Carbon401** [wvlia5/SublimeDebugger#25]
I'm using Sublime v3.0 build 3143 on OSX. Plugin is installed via package control. This is what I see in the console.

`ignored packages updated to: ["Anaconda", "Python Debugger", "QuickSimplenote", 
"SublimePythonIDE", "Vintage"]
`

Any way to resolve this?

**Comment by Carbon401** [comment]
Seems some package is not compatible with it. I removed most of them and it's not ignored anymore.

**Comment by matiasmorant** [comment]
OK. So should I just close this?

**Comment by Carbon401** [comment]
I'll try to figure out what exactly is causing this, post here and then close it. Maybe this will help someone else with similar problem.

[EDIT] Reinstalled from scratch and added all packages and this time it worked fine. Had to be something bad on my side. Closing.
