### ISSUE TITLE
Upload to Sublime Package Manager

### ISSUE THREAD

**Issue by matiasmorant** [wvlia5/SublimeDebugger#3]
Right now it can't be uploaded, there is a small modification that has to be done regarding keyboard shortcuts chosen.

**Comment by matiasmorant** [comment]
Relevant info https://github.com/wbond/package_control_channel/pull/6255

**Comment by pykong** [comment]
Simply change the key binding in question. Why open a separate issue for that?

BTW - PackageControl is rather slow with accepting new additions right now.
I have been waiting for weeks to get three tiny plugins accepted, despite all checks being successful.
Just be prepared it will not be a fast track to publish SublimeDebugger.

**Comment by matiasmorant** [comment]
Yes I know. Just to remember about it

**Comment by matiasmorant** [comment]
Solved
